Repository elastic/elasticsearch-labs, pull requests merged in 2023-08, with the labels that each got.

#10 Cleanup links and instructions
  colab-notebooks-examples/search/02-hybrid-search.ipynb
Labels: bug

#13 Fix sample data for question answering notebook
  notebooks/generative-ai/question-answering.ipynb
  notebooks/generative-ai/sample_data/data.json
Labels: bug

#12 Add contributing guidelines
  README.md
  docs/CONTRIBUTING.md
Labels: documentation

#29 Delete OpenAI Python integration example app
  CONTRIBUTING.md
  example-apps/OpenAI-embeddings/OpenAI-JS/README.md
  example-apps/OpenAI-embeddings/OpenAI-Py/.gitignore
  example-apps/OpenAI-embeddings/OpenAI-Py/LICENSE
  example-apps/OpenAI-embeddings/OpenAI-Py/README.md
  example-apps/OpenAI-embeddings/OpenAI-Py/generate_embeddings.py
  example-apps/OpenAI-embeddings/OpenAI-Py/images/elastic_cloud_id.png
  example-apps/OpenAI-embeddings/OpenAI-Py/images/elastic_credentials.png
  example-apps/OpenAI-embeddings/OpenAI-Py/images/openai_api_key.png
  example-apps/OpenAI-embeddings/OpenAI-Py/images/search.png
  example-apps/OpenAI-embeddings/OpenAI-Py/requirements.txt
  example-apps/OpenAI-embeddings/OpenAI-Py/sample_data/medicare.json
  example-apps/OpenAI-embeddings/OpenAI-Py/search_app.py
  example-apps/OpenAI-embeddings/OpenAI-Py/templates/search.html
  example-apps/OpenAI-embeddings/README.md
  example-apps/README.md
Labels: enhancement

#30 Add blog content reference in README.md
  README.md
Labels: documentation

#31 Add icon to blog content header
  README.md
Labels: documentation

#11 Showcase multilingual dense retrieval with E5
  notebooks/search/01-keyword-querying-filtering.ipynb
  notebooks/search/04-multilingual.ipynb
  notebooks/search/README.md
Labels: enhancement

#34 Update relevance benchmark app
  example-apps/relevance-workbench/app-api/Dockerfile
  example-apps/relevance-workbench/app-ui/src/pages/api/[...path].js
  example-apps/relevance-workbench/docker-compose.yml
Labels: bug

#33 Add readmes to notebook folders
  notebooks/generative-ai/README.md
  notebooks/generative-ai/question-answering.ipynb
  notebooks/integrations/README.md
  notebooks/integrations/hugging-face/README.md
  notebooks/integrations/hugging-face/loading-model-from-hugging-face.ipynb
  notebooks/integrations/llama-index/README.md
  notebooks/integrations/openai/README.md
  notebooks/langchain/README.md
Labels: documentation

#36 Fix typo that bugs markdown rendering
  example-apps/workplace-search/README.md
Labels: bug

#38 Update notebooks readme
  notebooks/generative-ai/README.md
Labels: documentation

#37 Add tiktoken dependency
  notebooks/generative-ai/chatbot.ipynb
Labels: bug

#39 Fix RAG prompt to pass top hit as context
  notebooks/integrations/openai/openai-KNN-RAG.ipynb
Labels: bug

#52 Import elasticsearch-labs Github repo in chatbot.ipynb
  notebooks/generative-ai/chatbot.ipynb
Labels: bug

#54 List all notebooks in root README
  README.md
Labels: documentation
